Bluetooth read data
nudge-reality/bluetooth-windows-rt pull request #4
Opened 2024-09-18 12:12 UTC by Fulons

To test:
 - Make sure BleWinrtDll project builds and produces a dll (this should now have the suffix of Debug in debug builds to avoid accidentally copying wrong dll)
 - Run DebugBle, all BLE devices ever connected to your pc will be listed in the console (if you have a connectionless BLE device change the device name (program.cs:23) to scan characteristics and attempt to read values)

closes #2

2024-09-18 15:51 UTC, SamHignett requested changes

2024-09-18 15:51 UTC, SamHignett commented on DebugBle/BLE.cs
> +#endif
![image](https://github.com/user-attachments/assets/28d210d1-5a51-4436-86ee-bfcf43191d90)

I could just be using it wrong, but even though I have my solution configuration set to "Debug", it is attempting to copy the non-debug version of the dll. 

Is this code snippet supposed to change which library is copied/loaded, or something else?

2024-09-18 15:51 UTC, SamHignett commented on DebugBle/BLE.cs
![image](https://github.com/user-attachments/assets/079d3e20-6bab-4752-b2a1-d52ffa7f477d)

After building both the debug/release version of the dll, and copying it to the `bluetooth-windows-rt\DebugBle` folder and running the application, it seems that no devices were found and the scan instantly finished. Previously the scan was  constant and found several devices of mine that should still be on. 

Does this mean the bluetooth device scanning did not work, do I need additional setup or is this simply a feature now that it won't show all devices unless you query them or something like that?

2024-09-19 14:56 UTC, d-blackburn submitted a review, later dismissed
LGTM! 👍🏼

2024-09-23 10:11 UTC, Fulons commented on DebugBle/BLE.cs
Check under Bluetooth & other devices in windows and ensure you have a paired BLE device (should not need to be connected)

2024-09-23 10:17 UTC, Fulons commented on BleWinrtDll/BleWinrtDll.cpp
> +					data->buf[i] = valueData[i];
Made sure index wont go out of range. Also added an error message to warn when this happens.

2024-09-23 10:49 UTC, SamHignett commented on DebugBle/BLE.cs
> +#endif
After running it again this morning, it seems to have copied the correct file now 👍 , no clue what changed though!

![image](https://github.com/user-attachments/assets/c3be4263-55e8-40e1-b8f2-0d1ae89c43fe)

Just to confirm in Rider that the post-build event script is correct.

2024-09-23 10:50 UTC, SamHignett commented on DebugBle/BLE.cs
Tested again with Bluetooth headphones paired and turned on, and it is now detecting them. 

It is curious how it was seemingly finding non-paired devices previously, but regardless it correctly detected a paired bluetooth device which is the goal.

2024-09-23 10:51 UTC, SamHignett approved these changes
LGTM! 👍

2024-09-23 10:51 UTC, merged